import type { Bindings } from "../../types";
import { brandMatch } from "./brand";
import { buildPayload } from "../qr/content";
import { encodeMatrix } from "../qr/encoder";
import { renderSvg } from "../qr/render-svg";

/**
 * QR Wallpaper — an AI-generated, brand-styled phone background with a real,
 * scannable QR composited on top.
 *
 * The background is generated by an image model (native FLUX). The QR itself is
 * NEVER drawn by the image model (that produces unscannable codes) — the client
 * composites our programmatic, scannable QR onto the background at the chosen
 * region. This module returns the background + the QR SVG + a layout spec.
 */

const IMAGE_MODEL = "@cf/black-forest-labs/flux-1-schnell";
const IMG_W = 768;
const IMG_H = 1280;

export type WallpaperStyle = "mesh" | "aurora" | "waves" | "minimal";
export type WallpaperPlacement = "top" | "center" | "bottom";

export const WALLPAPER_STYLES: WallpaperStyle[] = ["mesh", "aurora", "waves", "minimal"];
export const WALLPAPER_PLACEMENTS: WallpaperPlacement[] = ["top", "center", "bottom"];

export interface WallpaperResult {
  backgroundDataUrl: string;
  qrSvg: string;
  layout: { placement: WallpaperPlacement; qrFraction: number };
  palette: { fg: string; bg: string; accent: string };
  title: string;
  source: string;
  style: WallpaperStyle;
}

const STYLE_PROMPT: Record<WallpaperStyle, string> = {
  mesh: "soft flowing gradient mesh, smooth blurred color blends",
  aurora: "dreamy aurora light ribbons, soft glow, deep background",
  waves: "elegant flowing wave layers, smooth silky curves",
  minimal: "minimal soft gradient, lots of calm negative space, subtle grain",
};

const REGION_WORD: Record<WallpaperPlacement, string> = {
  top: "upper",
  center: "center",
  bottom: "lower",
};

/** A coarse color name from a hex, so the image prompt reads naturally. */
export function hexToName(hex: string): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return "neutral";
  const n = parseInt(m[1], 16);
  const r = (n >> 16) & 255,
    g = (n >> 8) & 255,
    b = n & 255;
  const max = Math.max(r, g, b),
    min = Math.min(r, g, b);
  const l = (max + min) / 2 / 255;
  if (max - min < 24) return l < 0.2 ? "near-black" : l > 0.85 ? "off-white" : "slate grey";
  let h = 0;
  const d = max - min;
  if (max === r) h = ((g - b) / d) % 6;
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  h = (h * 60 + 360) % 360;
  const names: [number, string][] = [
    [15, "red"], [45, "orange"], [70, "amber"], [160, "green"],
    [195, "teal"], [255, "blue"], [290, "indigo"], [330, "magenta"], [360, "red"],
  ];
  const base = names.find(([deg]) => h <= deg)?.[1] ?? "blue";
  return l < 0.35 ? `deep ${base}` : l > 0.7 ? `soft ${base}` : base;
}

/** Build the image-generation prompt for a brand wallpaper. Pure + testable. */
export function buildWallpaperPrompt(
  accent: string,
  style: WallpaperStyle,
  placement: WallpaperPlacement,
): string {
  const color = hexToName(accent);
  return [
    `premium abstract phone wallpaper, ${color} color palette`,
    STYLE_PROMPT[style],
    `clean calm empty space in the ${REGION_WORD[placement]} area for a panel`,
    "high quality, tasteful, modern, no text, no words, no letters, no logos, no qr code",
  ].join(", ");
}

/** Vertical placement → relative QR size fraction of the wallpaper width. */
export function placementLayout(placement: WallpaperPlacement): { placement: WallpaperPlacement; qrFraction: number } {
  return { placement, qrFraction: 0.46 };
}

async function generateBackground(env: Bindings, prompt: string): Promise<string | null> {
  // Workers AI image generation occasionally returns a transient upstream error;
  // retry a few times before giving up.
  const ATTEMPTS = 3;
  for (let attempt = 0; attempt < ATTEMPTS; attempt++) {
    try {
      const out = (await env.AI.run(IMAGE_MODEL, {
        prompt,
        width: IMG_W,
        height: IMG_H,
        steps: 6,
      })) as { image?: string };
      if (out?.image) {
        // FLUX returns base64; default container is JPEG.
        return `data:image/jpeg;base64,${out.image}`;
      }
    } catch (err) {
      if (attempt === ATTEMPTS - 1) console.error("[wallpaper] image gen failed:", err);
    }
  }
  return null;
}

export async function generateWallpaper(
  env: Bindings,
  rawUrl: string,
  opts: { style?: WallpaperStyle; placement?: WallpaperPlacement } = {},
): Promise<WallpaperResult | null> {
  const kit = await brandMatch(env, rawUrl);
  if (!kit) return null;

  const style: WallpaperStyle = WALLPAPER_STYLES.includes(opts.style as WallpaperStyle)
    ? (opts.style as WallpaperStyle)
    : "mesh";
  const placement: WallpaperPlacement = WALLPAPER_PLACEMENTS.includes(opts.placement as WallpaperPlacement)
    ? (opts.placement as WallpaperPlacement)
    : "center";

  // Cache the (expensive) background per domain+style.
  const cacheKey = `wp:${kit.source}:${style}`;
  let backgroundDataUrl: string | null = null;
  try {
    backgroundDataUrl = await env.SCAN_COUNTERS.get(cacheKey);
  } catch {
    /* miss */
  }
  if (!backgroundDataUrl) {
    backgroundDataUrl = await generateBackground(env, buildWallpaperPrompt(kit.palette.accent, style, placement));
    if (backgroundDataUrl) {
      try {
        await env.SCAN_COUNTERS.put(cacheKey, backgroundDataUrl, { expirationTtl: 86_400 });
      } catch {
        /* non-fatal */
      }
    }
  }
  if (!backgroundDataUrl) return null;

  // The QR is always our programmatic, scannable code (brand-styled design).
  let qrSvg: string;
  try {
    const matrix = encodeMatrix(buildPayload("url", { url: rawUrl }), kit.design.ecc);
    qrSvg = renderSvg(matrix, kit.design);
  } catch {
    return null;
  }

  return {
    backgroundDataUrl,
    qrSvg,
    layout: placementLayout(placement),
    palette: kit.palette,
    title: kit.title,
    source: kit.source,
    style,
  };
}
