import type { Bindings } from "../../types";
import { brandMatch, normalizeUrl } from "./brand";
import { buildPayload } from "../qr/content";
import { encodeMatrix } from "../qr/encoder";
import { renderSvg } from "../qr/render-svg";

/**
 * QR Wallpaper — an AI-generated, brand-styled phone background with a real,
 * scannable QR composited on top.
 *
 * The background is generated by an image model (native FLUX). The QR itself is
 * NEVER drawn by the image model (that produces unscannable codes) — the client
 * composites our programmatic, scannable QR onto the background at the chosen
 * region. This module returns the background + the QR SVG + a layout spec.
 */

// Quality-first chain: a refined aesthetic model, then a fast reliable fallback.
// Both are native Workers AI (gateway-free) and honor portrait width/height.
const IMAGE_MODELS = [
  "@cf/leonardo/phoenix-1.0", // most elegant; returns binary
  "@cf/black-forest-labs/flux-1-schnell", // fast fallback; returns base64
];
const IMG_W = 768;
const IMG_H = 1280;

// Native text model used to turn a brand's description into a visual scene motif.
const TEXT_MODEL = "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
const VISION_MODEL = "@cf/meta/llama-3.2-11b-vision-instruct";

export type WallpaperStyle = "mesh" | "aurora" | "waves" | "minimal" | "scene";
export type WallpaperPlacement = "top" | "center" | "bottom";

export const WALLPAPER_STYLES: WallpaperStyle[] = ["mesh", "scene", "aurora", "waves", "minimal"];
export const WALLPAPER_PLACEMENTS: WallpaperPlacement[] = ["top", "center", "bottom"];

export interface WallpaperResult {
  /** AI background; null when image gen was unavailable (client paints the gradient). */
  backgroundDataUrl: string | null;
  /** whether backgroundDataUrl came from the image model */
  aiBackground: boolean;
  /** always-available brand gradient so the wallpaper never fully fails */
  gradient: { from: string; via: string; to: string };
  qrSvg: string;
  layout: { placement: WallpaperPlacement; qrFraction: number };
  palette: { fg: string; bg: string; accent: string };
  title: string;
  /** brand/theme source host the look was derived from (e.g. "gamebyte.ai") */
  source: string;
  /** host the QR actually points to (e.g. "linkedin.com") — equals source unless decoupled */
  target: string;
  style: WallpaperStyle;
}

const STYLE_PROMPT: Record<WallpaperStyle, string> = {
  mesh: "flowing gradient mesh, soft blurred color fields melting together, organic blobs",
  aurora: "ethereal aurora light ribbons, luminous glow, deep atmospheric background, bokeh",
  waves: "elegant flowing wave layers, silky liquid curves, satin folds, smooth metallic sheen",
  minimal: "minimalist soft gradient, vast calm negative space, refined, airy, subtle film grain",
  // Themed/illustrative: a stylized scene evoking what the brand does (motif is
  // woven into the prompt head), still abstract enough to keep the QR scannable.
  scene: "rich stylized illustrative scene, depth and atmosphere, dynamic composition, painterly volumetric light, concept-art quality",
};

/** Premium quality cues appended to every wallpaper prompt. */
const QUALITY_CUES =
  "volumetric soft lighting, layered depth, smooth silky gradients, glossy sheen, fine detail, ultra high quality, 8k, award-winning, cinematic, sophisticated, tasteful";

/** Dedicated negative prompt (Leonardo/SDXL honor this field — keeps it clean). */
export const WALLPAPER_NEGATIVE =
  "text, words, letters, typography, watermark, signature, logo, qr code, phone, smartphone, device, screen, ui, app interface, frame, border, mockup, bezel, person, hand, low quality, blurry, noisy, jpeg artifacts, deformed, cluttered, oversaturated";

const REGION_WORD: Record<WallpaperPlacement, string> = {
  top: "upper",
  center: "center",
  bottom: "lower",
};

/** Clean display host for a URL (e.g. "linkedin.com"), or the trimmed input if unparseable. */
export function displayHost(raw: string): string {
  const u = normalizeUrl(raw);
  return u ? u.hostname.replace(/^www\./, "") : (raw || "").trim();
}

/** A coarse color name from a hex, so the image prompt reads naturally. */
export function hexToName(hex: string): string {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return "neutral";
  const n = parseInt(m[1], 16);
  const r = (n >> 16) & 255,
    g = (n >> 8) & 255,
    b = n & 255;
  const max = Math.max(r, g, b),
    min = Math.min(r, g, b);
  const l = (max + min) / 2 / 255;
  if (max - min < 24) return l < 0.2 ? "near-black" : l > 0.85 ? "off-white" : "slate grey";
  let h = 0;
  const d = max - min;
  if (max === r) h = ((g - b) / d) % 6;
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  h = (h * 60 + 360) % 360;
  const names: [number, string][] = [
    [15, "red"], [45, "orange"], [70, "amber"], [160, "green"],
    [195, "teal"], [255, "blue"], [290, "indigo"], [330, "magenta"], [360, "red"],
  ];
  const base = names.find(([deg]) => h <= deg)?.[1] ?? "blue";
  return l < 0.35 ? `deep ${base}` : l > 0.7 ? `soft ${base}` : base;
}

function clampByte(n: number): number {
  return Math.max(0, Math.min(255, Math.round(n)));
}

/** Scale a #RRGGBB toward black (<1) or white (>1). Falls back to a teal. */
export function shadeHex(hex: string, factor: number): string {
  const m = /^#?([0-9a-f]{6})$/i.exec((hex || "").trim());
  if (!m) return factor < 1 ? "#063040" : "#3FB6D6";
  const n = parseInt(m[1], 16);
  let r = (n >> 16) & 255,
    g = (n >> 8) & 255,
    b = n & 255;
  if (factor >= 1) {
    // lighten toward white
    const t = factor - 1;
    r = r + (255 - r) * t;
    g = g + (255 - g) * t;
    b = b + (255 - b) * t;
  } else {
    r *= factor;
    g *= factor;
    b *= factor;
  }
  return "#" + [r, g, b].map((c) => clampByte(c).toString(16).padStart(2, "0")).join("");
}

function luminance(hex: string): number {
  const m = /^#?([0-9a-f]{6})$/i.exec((hex || "").trim());
  if (!m) return 0.5;
  const n = parseInt(m[1], 16);
  return ((n >> 16) & 255) * 0.299 + ((n >> 8) & 255) * 0.587 + (n & 255) * 0.114;
}

/** A pleasing 3-stop brand gradient (always available, even with no AI image). */
export function gradientFromPalette(palette: { fg: string; accent: string }): {
  from: string;
  via: string;
  to: string;
} {
  // Use the accent unless it's near-white/near-black (poor gradient base) — then
  // fall back to the ink color, and if that's also flat, to a brand teal.
  let base = palette.accent;
  const lum = luminance(base);
  if (lum > 215 || lum < 18) {
    base = luminance(palette.fg) > 18 && luminance(palette.fg) < 215 ? palette.fg : "#0A7EA4";
  }
  return { from: shadeHex(base, 0.45), via: shadeHex(base, 0.8), to: shadeHex(base, 1.25) };
}

/**
 * Build the image-generation prompt for a brand wallpaper. Pure + testable.
 * `vibe` is an optional short brand style descriptor (from the brand image) so
 * the texture matches the brand's actual aesthetic, not just its color.
 * Describes a full-bleed texture — NOT a "phone wallpaper", which makes the model
 * paint a phone device/frame inside the image. Negatives live in WALLPAPER_NEGATIVE.
 */
export function buildWallpaperPrompt(
  accent: string,
  style: WallpaperStyle,
  placement: WallpaperPlacement,
  vibe?: string,
  motif?: string,
): string {
  const color = hexToName(accent);
  // The "scene" style leads with the brand's subject motif (what it does), so the
  // texture is thematic — e.g. a game studio gets neon game worlds, not just a
  // colour mesh. Abstract styles ignore the motif and stay clean.
  const head =
    style === "scene"
      ? `${color} stylized abstract scene${motif && motif.trim() ? `, themed around ${motif.trim()}` : ""}, full-bleed`
      : `${color} premium abstract background, full-bleed texture`;
  return [
    head,
    vibe && vibe.trim() ? vibe.trim() : "",
    STYLE_PROMPT[style],
    QUALITY_CUES,
    "fills the entire frame edge to edge, seamless, immersive, cohesive composition",
    `calm minimal negative space in the ${REGION_WORD[placement]} area`,
  ]
    .filter(Boolean)
    .join(", ");
}

/** Vertical placement → relative QR size fraction of the wallpaper width. */
export function placementLayout(placement: WallpaperPlacement): { placement: WallpaperPlacement; qrFraction: number } {
  // Prominent enough to scan from the image itself with any reader, not just a
  // focused phone camera.
  return { placement, qrFraction: 0.54 };
}

function bytesToBase64(bytes: Uint8Array): string {
  let bin = "";
  const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) {
    bin += String.fromCharCode(...bytes.subarray(i, i + CHUNK));
  }
  return btoa(bin);
}

/** Model-specific input. FLUX uses `steps`; Leonardo/SDXL use num_steps + guidance + negative_prompt. */
function inputFor(model: string, prompt: string, negative: string): Record<string, unknown> {
  const base = { prompt, width: IMG_W, height: IMG_H };
  if (model.includes("flux")) return { ...base, steps: 6 };
  // Leonardo Phoenix/Lucid: more steps + guidance + a real negative prompt = nicer output.
  return { ...base, num_steps: 25, guidance: 6, negative_prompt: negative };
}

/** Run one image model and normalize its output (base64 OR binary) to a data URL. */
async function runImageModel(
  env: Bindings,
  model: string,
  prompt: string,
  negative: string,
): Promise<string | null> {
  const out = (await env.AI.run(model, inputFor(model, prompt, negative))) as unknown;
  // FLUX-style: { image: base64 }
  if (out && typeof (out as { image?: unknown }).image === "string") {
    return `data:image/jpeg;base64,${(out as { image: string }).image}`;
  }
  // Leonardo/SDXL-style: raw binary (stream / buffer)
  let bytes: Uint8Array | null = null;
  if (out instanceof ReadableStream) bytes = new Uint8Array(await new Response(out).arrayBuffer());
  else if (out instanceof ArrayBuffer) bytes = new Uint8Array(out);
  else if (out instanceof Uint8Array) bytes = out;
  if (bytes && bytes.length) return `data:image/jpeg;base64,${bytesToBase64(bytes)}`;
  return null;
}

/**
 * Generate a background, trying each model (quality-first) with a couple of
 * retries each — Workers AI image gen occasionally returns a transient error.
 */
async function generateBackground(env: Bindings, prompt: string, negative: string): Promise<string | null> {
  for (const model of IMAGE_MODELS) {
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const url = await runImageModel(env, model, prompt, negative);
        if (url) return url;
      } catch (err) {
        console.error(`[wallpaper] ${model} attempt ${attempt + 1} failed:`, err);
      }
    }
  }
  return null;
}

/**
 * Vision-read the brand image into a short style descriptor (best-effort, cached
 * per domain) so the generated texture matches the brand's actual aesthetic.
 * Leonardo/Phoenix can't do img2img, so this is how we "use the brand image" —
 * the model describes it, and that description steers the text-to-image prompt.
 */
async function brandVibe(env: Bindings, source: string, imageUrl?: string): Promise<string | undefined> {
  if (!imageUrl) return undefined;
  const cacheKey = `wp:vibe:${source}`;
  try {
    const cached = await env.SCAN_COUNTERS.get(cacheKey);
    if (cached !== null) return cached || undefined;
  } catch {
    /* miss */
  }
  let vibe: string | undefined;
  try {
    const res = await fetch(imageUrl);
    if (res.ok) {
      const buf = new Uint8Array(await res.arrayBuffer());
      if (buf.length && buf.length <= 300_000) {
        const out = (await env.AI.run(VISION_MODEL, {
          image: [...buf],
          prompt:
            "Describe this brand's VISUAL STYLE as 4-6 short adjectives for an abstract wallpaper (e.g. 'sleek, futuristic, neon, dark'). Reply with ONLY comma-separated adjectives, no sentence.",
          max_tokens: 40,
        })) as { response?: string };
        const txt = (out?.response ?? "").replace(/\s+/g, " ").replace(/["'.]/g, "").trim();
        if (txt && txt.length <= 120) vibe = txt;
      }
    }
  } catch {
    /* best-effort */
  }
  try {
    await env.SCAN_COUNTERS.put(cacheKey, vibe ?? "", { expirationTtl: 86_400 });
  } catch {
    /* non-fatal */
  }
  return vibe;
}

/**
 * Turn a brand's title + description into a short visual SCENE MOTIF (what the
 * brand is about, as paintable nouns) so the "scene" style produces an on-theme
 * illustration — e.g. a game studio → "neon game worlds, arcade energy". Cached
 * per domain, best-effort (returns undefined → scene falls back to a stylish
 * abstract).
 */
async function brandMotif(
  env: Bindings,
  source: string,
  title: string,
  description?: string,
): Promise<string | undefined> {
  const cacheKey = `wp:motif:${source}`;
  try {
    const cached = await env.SCAN_COUNTERS.get(cacheKey);
    if (cached !== null) return cached || undefined;
  } catch {
    /* miss */
  }
  let motif: string | undefined;
  try {
    const brief = [title, description].filter(Boolean).join(" — ").slice(0, 400);
    const out = (await env.AI.run(TEXT_MODEL, {
      messages: [
        {
          role: "system",
          content:
            "You generate concise image-generation motifs. Given a brand, output 4-7 words of concrete VISUAL motifs (objects, environments, atmosphere) for an on-brand abstract wallpaper scene. No logos, no text, no brand names, no people. Reply with ONLY a comma-separated list, nothing else.",
        },
        { role: "user", content: `Brand: ${brief || source}` },
      ],
      max_tokens: 40,
    })) as { response?: string };
    const txt = (out?.response ?? "")
      .replace(/\s+/g, " ")
      .replace(/^["'\s]*(motifs?:)?\s*/i, "")
      .replace(/["'.]/g, "")
      .trim();
    if (txt && txt.length <= 140 && txt.includes(",")) motif = txt;
    else if (txt && txt.length <= 80) motif = txt;
  } catch {
    /* best-effort */
  }
  try {
    await env.SCAN_COUNTERS.put(cacheKey, motif ?? "", { expirationTtl: 86_400 });
  } catch {
    /* non-fatal */
  }
  return motif;
}

export async function generateWallpaper(
  env: Bindings,
  rawUrl: string,
  opts: { style?: WallpaperStyle; placement?: WallpaperPlacement; targetUrl?: string } = {},
): Promise<WallpaperResult | null> {
  // The brand/theme (colours, logo, background) comes from `rawUrl`. The QR can
  // point somewhere else entirely (`targetUrl`) — e.g. a gamebyte.ai-styled
  // wallpaper whose code opens your personal LinkedIn. Defaults to rawUrl.
  const kit = await brandMatch(env, rawUrl);
  if (!kit) return null;
  const destination = (opts.targetUrl ?? "").trim() || rawUrl;

  const style: WallpaperStyle = WALLPAPER_STYLES.includes(opts.style as WallpaperStyle)
    ? (opts.style as WallpaperStyle)
    : "mesh";
  const placement: WallpaperPlacement = WALLPAPER_PLACEMENTS.includes(opts.placement as WallpaperPlacement)
    ? (opts.placement as WallpaperPlacement)
    : "center";

  // Cache the (expensive) background per domain+style. The version prefix lets us
  // invalidate stale backgrounds when the generation prompt changes.
  const cacheKey = `wp:v4:${kit.source}:${style}`;
  let backgroundDataUrl: string | null = null;
  try {
    backgroundDataUrl = await env.SCAN_COUNTERS.get(cacheKey);
  } catch {
    /* miss */
  }
  if (!backgroundDataUrl) {
    // Read the brand's visual style from its image (best-effort) so the texture
    // matches the brand's aesthetic — the closest these text-to-image models get
    // to using the image as a reference.
    const vibe = await brandVibe(env, kit.source, kit.imageUrl);
    // The "scene" style additionally pulls a subject motif from the brand's
    // description (what it does) for a thematic, illustrative background.
    const motif =
      style === "scene" ? await brandMotif(env, kit.source, kit.title, kit.description) : undefined;
    const prompt = buildWallpaperPrompt(kit.palette.accent, style, placement, vibe, motif);
    backgroundDataUrl = await generateBackground(env, prompt, WALLPAPER_NEGATIVE);
    if (backgroundDataUrl) {
      try {
        await env.SCAN_COUNTERS.put(cacheKey, backgroundDataUrl, { expirationTtl: 86_400 });
      } catch {
        /* non-fatal */
      }
    }
  }
  // If image gen is unavailable, the client paints a brand gradient instead —
  // the wallpaper never fully fails.
  const aiBackground = !!backgroundDataUrl;

  // The QR is always our programmatic, scannable code (brand-styled design),
  // encoding the chosen destination (not necessarily the theme source).
  let qrSvg: string;
  try {
    const matrix = encodeMatrix(buildPayload("url", { url: destination }), kit.design.ecc);
    qrSvg = renderSvg(matrix, kit.design);
  } catch {
    return null;
  }

  return {
    backgroundDataUrl,
    aiBackground,
    gradient: gradientFromPalette(kit.palette),
    qrSvg,
    layout: placementLayout(placement),
    palette: kit.palette,
    title: kit.title,
    source: kit.source,
    target: displayHost(destination),
    style,
  };
}
